### ISSUE TITLE
CODEX 

### ISSUE THREAD

**Issue by Navya-web618** [Overengineering-squared/Overengineering-squared-RoboCup#1]
hello! 
Inspired by watching your previous runs we wanted to ask you some questions and tips for our first season participating in robocup, we have qualified for robocup Asia-Pacific. 

Ques-1) we are using machine learning for the rescue mission, but we are not using a torch. Till now we haven't faced any problems but according to you are there any problems that might occur?
Ques-2) This is our first season doing robocup, what are some problems that we might face ?
Ques-3) In the Resvue Mission, is there any chance that the ball might be touching a wall or the triangles?

**Comment by Skillnoob** [comment]
1. Do you mean pytorch or our LED's?
2. If you qualify for higher tournaments you should expect tiles you may haven't seen before. If you go through our videos from this year, you will see that the tiles got increasingly more complex. For example at the world championship there were green markers on ramps and obstacles on the ramp.
You should also bring spare parts for **everything** (except maybe really big parts), you never know what might break.
If you are using something like a Raspberry Pi or other SBC's. **Make a backup of the OS.**
3. Yes, that will always be the case. Usually the victims are placed roughly around the center of the evacuation zone, but your robot can obviously move them in inconvinient positions.

In general, I would reccomend having your code on a github respository, so you can easily roll back a change using GIT (you can google how to) if something went horribly wrong.

**Comment by Navya-web618** [comment]
Another question - 
is it allowed to you to place checkpoint wherever you want or the organisers place them themselves,
Also will, network will be provided by the organisers

Thank you

**Comment by Navya-web618** [comment]
I have another question which I have put on you Github page issue,
Waiting for your reply

**Comment by Skillnoob** [comment]
The organizers decide where to place the checkpoints, so its equal for everyone.
What do you mean by network? If you're talking about WIFI, we purchased a SIM Card Router and a sim card with unlimited data in the country we went to. It depends on the location if you get free WIFI by the organizers.
